fix: pre-commit and pre-push

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,7 +1,17 @@
-npm run lint || {
+npm run lint
+if [ $? -ne 0 ]; then
   echo "==================================================================="
   echo "❌ You can't push this code since Linting errors detected! ❌"
-  echo "💡 Note: You can use `npm run lint:fix` if you're lazy to fix!"
+  echo "💡 Note: You can use \`npm run lint:fix\` if you're lazy to fix!"
   echo "==================================================================="
   exit 1
-}
+fi
+
+npm run format
+if [ $? -ne 0 ]; then
+  echo "==================================================================="
+  echo "❌ You can't push this code since Code formatting issues detected! ❌"
+  echo "💡 Note: You can use \`npm run format:fix\` if you're lazy to fix!"
+  echo "==================================================================="
+  exit 1
+fi
